### PR TITLE
update information on queues

### PR DESCRIPTION
**Pull request by maggz69**
This documents the error resolution for users utilizing a different redis_client and the possibility that they may come across REDIS trying to create a connection when there isn't any connector for that connection

### CODE REVIEW

**Comment by maggz69** [comment]
This is from the discussion taking place here https://discord.com/channels/699055650549792778/699057717800599562/801053785329631272

**Comment by stancl** [comment]
I think that this is not related to queues but to the RedisTenancyBootstrapper 🤔  Do you have that bootstrapper enabled?

**Comment by maggz69** [comment]
I did not have the RedisBootstrapper enabled, only the QueuedBootstrapper.

**Comment by maggz69** [comment]
At the moment we have close to 11 redis clients listed. My mistake was not making use of either PHP_REDIS / PREDIS as a client and if you check the discord chat I linked above this did take quite a while to troubleshoot and debug. Had it been information added as a sidenote while setting up queues, I would have been long done with it. I do believe such an instance makes it helpful to the next dev in understanding the compatibility factor of queues and why a certain client is being used.

**Review by maggz69 — COMMENTED** [review]
Updating information to indicate utilising predis as well works.

**Comment by stancl** [comment]
Can you check if this happens when you disable CacheTenancyBootstrapper too?

I really don't see why this would be happening with the queues 🤔

**Pull request closed without merging**
