### PR TITLE
Update integration for laravel nova 4

### PR DESCRIPTION
**Pull request by adriaardila**
The previous configuration throws an error when setting up the middleware with 'web', you have to use 'nova' with nova v4.

### CODE REVIEW

**Comment by stancl** [comment]
The docs should cover both Nova 3 and Nova 4

**Comment by stancl** [comment]
Can you update the PR to cover both versions?

**Comment by stancl** [comment]
Actually we may do this task internally. There are more things that need to be changed for Nova 4 to work properly.

cc @abrardev99 can you check the changes I made in the SaaS boilerplate, `nova4` branch, and see what needs to be changed [here](https://sponsors.tenancyforlaravel.com/universal-central-and-tenant-nova)?

Create a task or a message on BC with that. We'll first update the sponsor doc page for the universal Nova and then we'll update the generic integration guide.

**Comment by BachirBichri** [comment]
This PR make the configuration not properly working with nova 3

**Comment by stancl** [comment]
Then see the previous version in this PR. Nova 4 is now the default in the integration guide

**Pull request merged**
