### PR TITLE
make apis first & consolidate to a single method

### PR DESCRIPTION
**Pull request by ahmedsayedabdelsalam**
https://laracasts.com/discuss/channels/code-review/laravel-8-route-problem

### CODE REVIEW

**Comment by stancl** [comment]
If Laravel uses web first, api second, I don't see why we'd change this against the standard?

**Comment by ahmedsayedabdelsalam** [comment]
laravel uses apis first, they had issues when they did that.

image

**Comment by stancl** [comment]
Ah I see. I think this logic is also managed by our automatic installer, so I'll look into this during v4. Thanks!

**Comment by abrardev99** [comment]
They just [swapped the order back](https://github.com/laravel/laravel/commit/292a5b26a9293d82ab5a7d0bb81bba02ea71758e) in Laravel.

**Comment by stancl** [comment]
Thanks for finding that. Also, do the calls need to be wrapped in that `routes()` call?

**Comment by abrardev99** [comment]
>  do the calls need to be wrapped in that routes() call?

Laravel started wrapping routes in `routes()` call in `L8`. So, looks like we don't necessarily need to wrap in a `routes()` call, and it will work.

**Comment by stancl** [comment]
Can you find why Laravel does that?

**Comment by abrardev99** [comment]
> Can you find why Laravel does that?

I'm not sure why. But calling the `$this->routes` set a property in the base provider. And Laravel registers routes based on the property like 

```
protected function loadRoutes()
    {
        if (! is_null($this->loadRoutesUsing)) {
            $this->app->call($this->loadRoutesUsing);
        } elseif (method_exists($this, 'map')) {
            $this->app->call([$this, 'map']);
        }
    }
```

If the property is null, it calls the `map` method, which was used in `L7`. 

What I think, as we are using the `boot` method, routes get registered anyway. I still do not understand why routes got registered without the `$this->routes` call, maybe due to the `boot` method. I think we should be documenting this way of registering routes which OP PR is doing. Laravel says, `consolidate to a single method`.

**Comment by ahmedsayedabdelsalam** [comment]
it's added here in this comment https://github.com/laravel/laravel/commit/a9abc85301ab56a89f5c7256dfbc30f8dd0abafd 
and i think it's just optional and sort of grouping route registering together in a single call. kinda of code formatting.

**Comment by stancl** [comment]
Merging after our discussion on Basecamp. Thanks for the PR!

**Pull request merged**
