### PR TITLE
Added migration file sample

### PR DESCRIPTION
**Pull request by kakajansh**

### CODE REVIEW

**Comment by stancl** [comment]
Creating a migration is optional. You may want to do it step by step and create a sql dump, for example.

**Comment by kakajansh** [comment]
I think it should work for most cases. This makes v2 migrations to be compatible with v3. If not add timestamp fields when creating new Tenant it will throw __created_at__ / __updated_at__ fields not found.

**Comment by stancl** [comment]
Ah didn't see the diff on mobile, this doesn't include the changes to tenant data.

Probably looks good then.

Can you confirm that `$table->increments('id')->first();` in `domains` works & makes it AI? When a friend was testing this, only `primary()` worked for him. Making it AI didn't work.

Also, wouldn't `bigIncrements` be more in line with Laravel ID standards?

Thanks!

**Comment by kakajansh** [comment]
> Can you confirm that $table->increments('id')->first(); in domains works & makes it AI? When a friend was testing this, only primary() worked for him. Making it AI didn't work.

For me, mysql v5.7 works well. So I removed manually updating IDs as it done with AI column automatically.
Actually I don't see any reason to not work. Maybe he added ID column before manually and conflicting with this.

> Also, wouldn't bigIncrements be more in line with Laravel ID standards? 

Yes maybe, but mostly tried to keep in line with [2019_09_15_000020_create_domains_table.php](https://github.com/stancl/tenancy/blob/a0192a941e36a1590cf8c2e13619b8a4a6213ff4/assets/migrations/2019_09_15_000020_create_domains_table.php#L19)

**Comment by stancl** [comment]
Ah. Do you think it's worth change that to UNSIGNED BIG INTEGER for consistency with standard Laravel migrations?

Though some people say that the INTEGER limit is very rarely reached, so it's probably not a problem.

If the migration worked for you, I'll merge this. Since (I assume) you tried migrating a v2 app to v3, can you confirm that the upgrade guide is correct? I have a disclaimer that it might not be 100%, so I could remove that.

I'd like to test the upgrade guide with a v2 app I have locally, but I don't want to delay the v3 release with that and I can always  go back and update the guide.

**Comment by kakajansh** [comment]
> Ah. Do you think it's worth change that to UNSIGNED BIG INTEGER for consistency with standard Laravel migrations?
>
> Though some people say that the INTEGER limit is very rarely reached, so it's probably not a problem.

I think so, there will be rare situations. As BIGINT uses more disk space personally prefer just INTs

[BIGINT v INT. Is there a big deal?](http://ronaldbradford.com/blog/bigint-v-int-is-there-a-big-deal-2008-07-18/)
**INT[(M)] [UNSIGNED] [ZEROFILL]**
A normal-size integer. The signed range is -2147483648 to 2147483647. The unsigned range is 0 to 4294967295.

**BIGINT[(M)] [UNSIGNED] [ZEROFILL]**
A large integer. The signed range is -9223372036854775808 to 9223372036854775807. The unsigned range is 0 to 18446744073709551615.




___

> can you confirm that the upgrade guide is correct?

One thing was not mentioned adding `App\Providers\TenancyServiceProvider::class` to providers list.


And the issue I was experiencing is: 
- Main app **shop.test**. 
- Tenant apps **foo.shop.test** and **bar.shop.test**. 

In v2 I have saved tenant domains as **foo.shop.test**
But in v3 I get **TenantCouldNotBeIdentifiedOnDomainException**, only saving tenant subdomains without main domain as **foo**  and **bar** works

**Comment by stancl** [comment]
Should be fine then, thanks!

**Pull request merged**
