### PR TITLE
spatie/laravel-login-link Installation

### PR DESCRIPTION
**Pull request by secrethash**
Installation Instructions for spatie/laravel-login-link

### CODE REVIEW

**Comment by stancl** [comment]
@lukinovec Can you test this locally and fix up the writing/formatting?

**Comment by secrethash** [comment]
Hey @stancl how to add a link to a page? I feel that the **Tenant Identification** page should be linked too.

I looked at other doc pages and saw that you have used `{{ $page->link('domains) }}` so after looking up a bit I think it should be `{{ $page->link('tenant-identification') }}`? Is it correct?

**Comment by stancl** [comment]
Yeah

**Comment by stancl** [comment]
@lukinovec is this ready to be merged now?

**Comment by lukinovec** [comment]
> @lukinovec is this ready to be merged now?

Yeah

**Pull request merged**
